service: sat-anti-luddite
frameworkVersion: '1.61.2' # plugin 이슈 https://github.com/serverless-heaven/serverless-aws-alias/issues/181

plugins:
  - serverless-plugin-typescript
  - serverless-aws-alias

custom:
  environment: ${opt:alias, self:provider.stage}

provider:
  name: aws
  stage: 'stage'
  runtime: nodejs12.x
  profile: ipf
  region: ap-northeast-2
  timeout: 15
  tags:
    service: sat
    environment: common
    owner: hpark
  role: arn:aws:iam::572836591883:role/sat-anti-luddite-lambda
  environment: ${file(environment-variables.yml):${self:custom.environment}}
  stackName: sat-anti-luddite-stack
  stackTags:
    service: sat
    environment: ${self:custom.environment}
    owner: hpark
  deploymentBucket:
    name: ipf-release-ci-seoul
    tags:
      service: sat
      environment: ${self:custom.environment}
      owner: hpark

functions:
  request-stt-analysis:
    handler: src/stt/handler-request-stt-analysis.handler
    timeout: 120
  save-stt-result:
    handler: src/stt/handler-save-stt-result.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.transcribe'
            detail-type:
              - 'Transcribe Job State Change'
            detail:
              TranscriptionJobStatus:
                - COMPLETED
  ocr-body-filter:
    handler: src/ocr/handler-ocr-body-filter.handler
    events:
      - sns: sat-anti-luddite-ocr-body-filter
  request-ocr-analysis-and-save-result:
    handler: src/ocr/handler-request-ocr-analysis-and-save-result.handler
    timeout: 420
  invoke-ocr-function-by-bid:
    handler: src/ocr/handler-invoke-ocr-function-by-bid.handler
  request-bind-sentence:
    handler: src/sentence-binder/handler-request-bind-sentence.handler
    timeout: 300
  add-playable-sentence:
    handler: src/playable-sentence/handler.add
    events:
      - http:
          path: api/sentence
          method: post
  get-playable-sentence:
    handler: src/playable-sentence/handler.get
    events:
      - http:
          path: api/sentence
          method: get
package:
  exclude:
    - '*.yml'
