service: sat-anti-luddite
frameworkVersion: '>=1.34 <2.0.0'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  profile: ipf
  region: ap-northeast-2
  timeout: 15
  tags:
    service: sat
    environment: common
    owner: hpark
  role: arn:aws:iam::572836591883:role/sat-anti-luddite-lambda
  environment: ${file(environment-variables.yml)}
  stackName: sat-anti-luddite-stack
  stackTags:
    service: sat
    environment: common
    owner: hpark
  deploymentBucket:
    name: ipf-release-ci-seoul
    tags:
      service: sat
      environment: common
      owner: hpark

functions:
  request-stt-analysis:
    handler: src/request-stt-analysis.handler
    timeout: 120
  save-stt-result:
    handler: src/save-stt-result.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.transcribe'
            detail-type:
              - 'Transcribe Job State Change'
            detail:
              TranscriptionJobStatus:
                - COMPLETED
  ocr-body-filter:
    handler: src/ocr-body-filter.handler
    events:
      - sns: sat-anti-luddite-ocr-body-filter
  request-ocr-analysis-and-save-result:
    handler: src/request-ocr-analysis-and-save-result.handler
    timeout: 420
  invoke-ocr-function-by-bid:
    handler: src/invoke-ocr-function-by-bid.handler

package:
  exclude:
    - '*.yml'